import create from 'zustand';

export const useGameStore = create((set) => ({
  grid: Array(9).fill(null).map(() => Array(9).fill(0)),
  myTurn: true,
  mySign: -1,
  waiting: true,
  oppName: null,
  oppSocketId: null,
  gameOver: false,
  endGameText: null,
  metaGrid: Array(9).fill(0),
  activeGridPosition: 4,
  setGrid: (grid) => set({ grid }),
  setMyTurn: (myTurn) => set({ myTurn }),
  setMySign: (mySign) => set({ mySign }),
  setWaiting: (waiting) => set({ waiting }),
  setOppName: (oppName) => set({ oppName }),
  setOppSocketId: (oppSocketId) => set({ oppSocketId }),
  setGameOver: (gameOver) => set({ gameOver }),
  setEndGameText: (endGameText) => set({ endGameText }),
  setMetaGrid: (metaGrid) => set({ metaGrid }),
  setActiveGridPosition: (activeGridPosition) => set({ activeGridPosition }),
  resetGame: () => set({
    grid: Array(9).fill(null).map(() => Array(9).fill(0)),
    myTurn: true,
    mySign: -1,
    waiting: true,
    oppName: null,
    oppSocketId: null,
    gameOver: false,
    endGameText: null,
    metaGrid: Array(9).fill(0),
    activeGridPosition: 4,
  }),
}));
